=== willharto/stendhal/data/conf/achievements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	    xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	    xmlns:Q1="stendhal">
	    
	    <element name="achievements" type="Q1:achievementGroup"></element>
	    
	    <complexType name="Q1:achievementGroup">
	    		<sequence>
	    				<element name="achievement" type="Q1:achievementType" minOccurs="0" maxOccurs="unbounded"></element>
	    		</sequence>
	    </complexType>
	    
	    <complexType name="achievementType">
	    		<sequence>
	    				<element name="identifier" type="Q1:attribute"/>
	    				<element name="title" type="Q1:attribute"></element>
	    				<element name="description" type="Q1:attribute"></element>
	    				<element name="score" type="Q1:attribute"></element>
	    				<element name="active" type="boolean"></element>
	    				<element name="condition" type="Q1:condition" minOccurs="0"></element>
	    		</sequence>
	    </complexType>
	    
	    <complexType name="condition">
	    		<attribute name="name" type="string"></attribute>
	    		<attribute name="parameters" type="Q1:parameter"></attribute>
	    </complexType>
	    
	    <complexType name="parameters">
	    		<attribute name="type" type="string"></attribute>
	    		<attribute name="value" type="string"></attribute>
	    </complexType>
	    
	    <complexType name="attribute">
	    		<attribute name="value" type="string"></attribute>
	    </complexType>
</schema>

=== willharto/stendhal/tests/games/stendhal/server/core/config/achievementstest.xml
<?xml version="1.0" encoding="UTF-8"?>		
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="../achievements.xsd ">
	
	<achievement
		identifier="item.money.100"
		category="ITEM"
		title="First pocket money"
		description="Loot 100 money from creatures"
		score=EASY_BASE_SCORE
		active=true>
		<condition condition ="PlayerLootedNumberOfItemsCondition" value="100|money"
		
		</condition>
	</achievement>
	
	
	<achievement
		identifier="xp.level.010"
		category="EXPERIENCE"
		title="Greenhorn"
		description="Reach level 10"
		score=EASY_BASE_SCORE
		active=true>
		<condition condition ="LevelGreaterThanCondition" value="9"
		
		</condition>
	</achievement>
	
	<achievement
		identifier="xp.level.050"
		category="EXPERIENCE"
		title="Novice"
		description="Reach level 5"
		score=EASY_BASE_SCORE
		active=true>
		<condition condition ="LevelGreaterThanCondition" value="49"
		
		</condition>
		
	</achievement>
	
	
	<achievement
		identifier="fight.general.rats"
		category="fighting"
		title="Rat Hunter"
		description="Kill 15 rats"
		score=1
		active=true
		condition="PlayerHasKilledNumberOfCreaturesCondition" value = "rat|15"
	</achievement>
	
	
	
</achievements>
